language: c
script: make && make check
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
sudo: false
matrix:
  include:
    - language: ruby
      rvm: 2.3.3
      script: make acceptance
      env: NAME="Acceptance Tests"
      dist: trusty
      compiler:
      addons:
        apt:
          packages:
          - tmux
